apiVersion: v1
kind: ReplicationController
metadata:
  name: webinar-flask-rc
spec:
  replicas: 3
  selector:
    name: webinar-flask
    version: v8
  template:
    metadata:
      labels:
        name: webinar-flask
        version: v8
    spec:
      containers:
        - name: db
          image: redis
          ports:
            - containerPort: 6379
        - name: web
          image: gcr.io/webinar-06272018/webinar-flask
          ports:
            - containerPort: 5000
